#!/bin/bash

#------------------------------------------------------------------------

brightness() {
  echo "$(xbacklight -get | cut -d'.' -f1)%"
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  #3) pamixer --toggle-mute ;;  # right click, mute/unmute
  4) xbacklight -inc 10 ;; # scroll up, increase
  5) xbacklight -dec 10 ;; # scroll down, decrease
esac

brightness
